### PR TITLE
Update build.gradle

### PR DESCRIPTION
**Pull request by seventhmoon**
updated library dependency

### CODE REVIEW

**Comment by ryanseys** [comment]
Can you explain what this PR is meant to accomplish and how this is a positive change for the library?

**Comment by seventhmoon** [comment]
1. since appcompat-v7 already include support-v4, so I removed support-v4 in the build.gradle. (clean up)
2. I updated the version of the library used to its latest version (keeping this project up-to-date)

**Comment by ryanseys** [comment]
Cool, can you update to 22.2.1 now and I'll get it merged in.

```
compile 'com.android.support:recyclerview-v7:22.2.1'
compile 'com.android.support:leanback-v17:22.2.1'
compile 'com.android.support:appcompat-v7:22.2.1'
compile 'com.github.bumptech.glide:glide:3.6.1'
```

**Comment by seventhmoon** [comment]
Done.

**Comment by ryanseys** [comment]
Thanks!

**Pull request merged**
